Początek progrmu\
**pogrubiony tekst**\
Nowa linia

# Nowa Sekcja
## Nowa sekcja
### Nowa sekcja

In [1]:
print('Witaj w notatniku...')

Witaj w notatniku...


In [2]:
a = 5
b = 6

In [3]:
print(a, b)

5 6


In [4]:
a

5

In [ ]:
c = 9

Celowo nie uruchamiam komórki c = 9

In [6]:
print(c)

NameError: name 'c' is not defined

# Biblioteka NumPy

Napisana w C do szybkich operacji na danych tablicowych\
Podstawowy element ndarray

In [7]:
!pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------  12.6/12.8 MB 91.2 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 47.5 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import numpy as np

In [9]:
print(np.__version__)

2.3.4


In [10]:
lista = [2, 4, 6, 8, 10]
lista

[2, 4, 6, 8, 10]

In [11]:
a = np.array(lista)
a

array([ 2,  4,  6,  8, 10])

In [13]:
a.dtype

dtype('int64')

int64 - 8 bajtów

In [14]:
type(a)

numpy.ndarray

In [15]:
a.shape  # kształt

(5,)

In [16]:
p = np.zeros((3, 3))
p

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
print(p)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
print(p.dtype)

float64


In [19]:
q = np.ones((2, 2))
print(q)
q.dtype

[[1. 1.]
 [1. 1.]]


dtype('float64')

In [20]:
r = np.full((2, 2), 4)
print(r)
print(r.dtype)

[[4 4]
 [4 4]]
int64


In [21]:
s = np.eye(4)
print(s)
s.dtype

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


dtype('float64')

In [23]:
t = np.random.random((3, 3))
print(t)
print(t.dtype)

[[0.79554053 0.85198422 0.0919179 ]
 [0.18866589 0.30809568 0.73779778]
 [0.09870301 0.7346335  0.20017671]]
float64


In [24]:
lista2 = [[5, 6], [7, 8]]
b = np.array(lista2)
print(lista2)
print(b)

[[5, 6], [7, 8]]
[[5 6]
 [7 8]]


In [25]:
# ravel() - spłąszczenie, zwraca nowy obiekt
print(b.ravel())

[5 6 7 8]


In [26]:
# b sie nie zmienia
b[0]

array([5, 6])

In [27]:
print(b[0, 0])
b[0, 1]

5


np.int64(6)

In [28]:
print(np.float64(21))

21.0


In [29]:
print(np.int64(22.0))

22


In [30]:
print(np.bool(21))

True


In [31]:
print(np.float64(True))

1.0


In [35]:
arr = np.arange(1, 11, dtype=np.float64)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [36]:
arr.dtype

dtype('float64')

In [37]:
# reshape() - zmiana kształtu
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
new_arr = arr.reshape(4, 3)
new_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
print(new_arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [40]:
new_arr = arr.reshape(3, 4)
new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
print(new_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
new_arr = arr.reshape(3, 5)
new_arr

ValueError: cannot reshape array of size 12 into shape (3,5)

In [43]:
new_arr = arr.reshape(3, 3)
new_arr

ValueError: cannot reshape array of size 12 into shape (3,3)