Początek progrmu\
**pogrubiony tekst**\
Nowa linia

# Nowa Sekcja
## Nowa sekcja
### Nowa sekcja

In [1]:
print('Witaj w notatniku...')

Witaj w notatniku...


In [2]:
a = 5
b = 6

In [3]:
print(a, b)

5 6


In [4]:
a

5

In [ ]:
c = 9

Celowo nie uruchamiam komórki c = 9

In [6]:
print(c)

NameError: name 'c' is not defined

# Biblioteka NumPy

Napisana w C do szybkich operacji na danych tablicowych\
Podstawowy element ndarray

In [7]:
!pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------  12.6/12.8 MB 91.2 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 47.5 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import numpy as np

In [9]:
print(np.__version__)

2.3.4


In [10]:
lista = [2, 4, 6, 8, 10]
lista

[2, 4, 6, 8, 10]

In [11]:
a = np.array(lista)
a

array([ 2,  4,  6,  8, 10])

In [13]:
a.dtype

dtype('int64')

int64 - 8 bajtów

In [14]:
type(a)

numpy.ndarray

In [15]:
a.shape  # kształt

(5,)

In [16]:
p = np.zeros((3, 3))
p

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
print(p)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
print(p.dtype)

float64


In [19]:
q = np.ones((2, 2))
print(q)
q.dtype

[[1. 1.]
 [1. 1.]]


dtype('float64')

In [20]:
r = np.full((2, 2), 4)
print(r)
print(r.dtype)

[[4 4]
 [4 4]]
int64


In [21]:
s = np.eye(4)
print(s)
s.dtype

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


dtype('float64')

In [23]:
t = np.random.random((3, 3))
print(t)
print(t.dtype)

[[0.79554053 0.85198422 0.0919179 ]
 [0.18866589 0.30809568 0.73779778]
 [0.09870301 0.7346335  0.20017671]]
float64


In [24]:
lista2 = [[5, 6], [7, 8]]
b = np.array(lista2)
print(lista2)
print(b)

[[5, 6], [7, 8]]
[[5 6]
 [7 8]]


In [25]:
# ravel() - spłąszczenie, zwraca nowy obiekt
print(b.ravel())

[5 6 7 8]


In [26]:
# b sie nie zmienia
b[0]

array([5, 6])

In [27]:
print(b[0, 0])
b[0, 1]

5


np.int64(6)

In [28]:
print(np.float64(21))

21.0


In [29]:
print(np.int64(22.0))

22


In [30]:
print(np.bool(21))

True


In [31]:
print(np.float64(True))

1.0


In [35]:
arr = np.arange(1, 11, dtype=np.float64)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [36]:
arr.dtype

dtype('float64')

In [37]:
# reshape() - zmiana kształtu
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
new_arr = arr.reshape(4, 3)
new_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
print(new_arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [40]:
new_arr = arr.reshape(3, 4)
new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
print(new_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
new_arr = arr.reshape(3, 5)
new_arr

ValueError: cannot reshape array of size 12 into shape (3,5)

In [43]:
new_arr = arr.reshape(3, 3)
new_arr

ValueError: cannot reshape array of size 12 into shape (3,3)

ravel() - zwraca widok
operacja na "widoku" wpływnie na oryginalną tablicę

flatten() - zwraca kopię
zmiany nie wpłyną na oryginalną tablicę

In [44]:
print(new_arr.ravel())  # widok

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [45]:
print(new_arr.flatten())  # kopia

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [46]:
flat = new_arr.flatten()
rav = new_arr.ravel()

In [47]:
flat[0] = 999  # kopia
rav[1] = 888  # widok

In [48]:
print(new_arr)  # rav[1] zaminiło wartość w oryginalnej tablicy

[[  0 888   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


-------
### transpose() - zamienia osie

In [49]:
print(new_arr.transpose())

[[  0   4   8]
 [888   5   9]
 [  2   6  10]
 [  3   7  11]]


---------
### resize() - zmienia rozmiar tablicy
zmienia oryginalną tablicę (in-place)
brakujące eleemnty uzupełnia zerami

In [50]:
new_arr.resize(1, 12)
print(new_arr)

[[  0 888   2   3   4   5   6   7   8   9  10  11]]


In [51]:
arr1 = np.arange(1, 10).reshape(3, 3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Broadcasting
Wykonaje operacje na wszystkich elementach macierzy

In [52]:
lista = [1, 2, 3]
print(2 * lista)

[1, 2, 3, 1, 2, 3]


In [54]:
print(list(map(lambda x: x * 2, lista)))

[2, 4, 6]


In [53]:
arr2 = 2 * arr1
print(arr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [57]:
arrx = arr1 + arr2
print(arrx)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


## Zasady broadcastingu

Wymiary muszą być zgodne\
1. Dwa wymiary są zgodne jeśli:
    - są równe, lub jeden z nich ma wymiar 1
2. Jeśli nie spełniają tych earunkow -> ValueError

------
hstack() - skleja tablice poziomo

In [59]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
print(arr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [58]:
arr3 = np.hstack((arr1, arr2))
print(arr3)

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


------
vstack() - skleja poziomo

In [61]:
arr4 = np.vstack((arr1, arr2))
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


---------
concatenate() - sklejanie w wybranej osi

In [62]:
arr5 = np.concatenate((arr1, arr2), axis=0)  # wiersze
print(arr5)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [63]:
arr6 = np.concatenate((arr1, arr2), axis=1)  # kolumny
print(arr6)

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


------
Tworzy tablicę z sekwencji

In [64]:
arre1 = np.array([1, 2, 3])
print(arre1)

[1 2 3]


In [65]:
arre2 = np.array([4, 5, 6])
print(arre2)

[4 5 6]


In [67]:
np.concatenate((arre1, arre2), axis=0)

array([1, 2, 3, 4, 5, 6])

In [68]:
np.concatenate((arre1, arre2), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [69]:
print(arre1)
print(arre1.shape)

[1 2 3]
(3,)


In [71]:
print(arre2)
print(arre2.shape)

[4 5 6]
(3,)


-------
dstack() - skleja tablice  w głąb, dodaje trzeci wymiar

In [72]:
arr7 = np.dstack((arr1, arr2))
print(arr7)

[[[ 1  2]
  [ 2  4]
  [ 3  6]]

 [[ 4  8]
  [ 5 10]
  [ 6 12]]

 [[ 7 14]
  [ 8 16]
  [ 9 18]]]


--------
column_stack - skleja jako kolumny

In [73]:
arr8 = np.arange(4, 7)
print(arr8)

[4 5 6]


In [74]:
arr9 = 2 * arr8
print(arr9)

[ 8 10 12]


In [75]:
arr_col_stack = np.column_stack((arr8, arr9))
print(arr_col_stack)

[[ 4  8]
 [ 5 10]
 [ 6 12]]


------
row_stack() - jako wiersze

In [76]:
arr_row_stack = np.row_stack((arr8, arr9))
print(arr_row_stack)

[[ 4  5  6]
 [ 8 10 12]]


C:\Users\CSComarch\AppData\Local\Temp\ipykernel_15036\2282068895.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  arr_row_stack = np.row_stack((arr8, arr9))


In [77]:
result_vstack = np.vstack((arr8, arr9))
print(result_vstack)

[[ 4  5  6]
 [ 8 10 12]]


---------
hsplit() - dzieli w poziomie

In [78]:
arr10 = np.arange(1, 10).reshape(3, 3)
print(arr10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [79]:
arr_split = np.hsplit(arr10, 3)
print(arr_split)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


-------
vsplit - dzieli na wiersze

In [80]:
arr_v_split = np.vsplit(arr10, 3)
print(arr_v_split)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [81]:
arr_v_split

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [82]:
arr11 = np.arange(1, 10).reshape(3, 3)
print("Tablicy w typie integer:", arr1.dtype)

Tablicy w typie integer: int64


In [83]:
# konwersja tablicy na inny typ
# tworzy nową tablicę
arr12 = arr1.astype(float)
print("Zmieniony typ na:", arr12.dtype)

Zmieniony typ na: float64


In [84]:
# zamiana na liste pythonową
list1 = arr1.tolist()
print("Lista pythonowa:", list1)
print("Typ listy:", type(list1))

Lista pythonowa: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Typ listy: <class 'list'>


------
copy() - kopia listy

In [85]:
arr13 = np.arange(1, 5).reshape(2, 2)
print(arr13)

[[1 2]
 [3 4]]
